[package]
name = "bak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copy_dir="0.1.3"

[[bin]] 
name = "bak"

[[bin]]
name = "unbak"
